
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TestGYApp.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Clients
{

    public int ID { get; set; }

    public string FullName { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Patronymic { get; set; }

    public Nullable<System.DateTime> BirthDate { get; set; }

    public Nullable<short> Age { get; set; }

    public Nullable<bool> IsChild { get; set; }

    public Nullable<bool> IsOldMan { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Comment { get; set; }

    public Nullable<bool> Deleted { get; set; }

    public string cl_name { get; set; }

    public Nullable<int> MarketingInfo { get; set; }



    public virtual MarketingInfoChoice MarketingInfoChoice { get; set; }

}

}
